### ISSUE TITLE
[Bug]: TypeMismatch error when using getStarterPack function

### ISSUE THREAD

**Issue by andylin2004** [MasterJ93/ATProtoKit#55]
### Summary

TypeMismatch error when using getStarterPack function with a URI from a StarterPackViewBasicDefinition

### Reproduction Steps

Use the getStarterPack function with a known good starterPackURI (you can verify with this starter pack URI: at://did:plc:kk2a54fcplihszfwvzqprfwn/app.bsky.graph.starterpack/3lbk3g37cn32w) in a project after you have authenticated a user with the ATProtocolConfiguration initializer and the authenticate function. The getStarterPack function will then error out.

### Expected Results

I was expecting the getStarterPack function to decode the remote response correctly and return a GetStarterPackOutput struct containing the appropriate data.

### Actual Results

I got an error: 

typeMismatch(Swift.Array<Any>, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "starterPack", intValue: nil)], debugDescription: "Expected to decode Array<Any> but found a dictionary instead.", underlyingError: nil))

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS

### Operating System Version

Seqouia 15.1

### ATProtoKit Version

0.19.2

**Comment by MasterJ93** [comment]
Please try the `develop` branch as I believe the bugs I've fixed in there have solved that issue. I plan on releasing them in a future version soon (sometime next week: I'm still fixing a few more bugs).

**Comment by andylin2004** [comment]
Hmm, I just checked and the error still seems to be there. I do also believe there's a regression in the develop branch, as now the potential parameter for enum embedRecordView for a post embed fails to get the start pack one (it gets loaded as a labelerview instead).

**Comment by MasterJ93** [comment]
Looks like I used the wrong `struct`. That's on me: I'll fix that up right now.

As for the regression, I'll investigate that further.

**Comment by MasterJ93** [comment]
Do you mind sending me the full error for the second issue? I'm looking at the code and I don't see anything that makes gives you a labeler view instead of a starter pack.

**Comment by andylin2004** [comment]
It doesn't actually seem to generate an error, as this issue seems to be more of a case where after using the getAuthorFeed on a known good author DID, it will correctly get the author feed JSON from Bluesky, but fail to decode the JSON correctly as posts that contain an embed that then contains a record of type app.bsky.graph.starterpack will have the record decoded as if it was a app.bsky.labeler.defs#labelerView incorrectly.

**Comment by MasterJ93** [comment]
After looking at the post URI, I can indeed confirm what you're saying is true. This shouldn't be happening, as the labelerView and starterPackBasic have different requirements.

Weirdly enough, if I disable the labelerView check, it will decode the starter pack correctly. There must be something in the JSON object that makes ATProtoKit think it's a labelerView, but looking at the lexicons, both have slight differences in requirements.

I'll look more closely in terms of what the structs need and figure out how to best make this work without changing the layout: if I change the layout, then it's possible the opposite could happen (that is, a labeller could be decoded incorrectly into a starter pack).
