### ISSUE TITLE
[Bug]: Decoding Error for getTimeline: app.bsky.embed.images#view not defined

### ISSUE THREAD

**Issue by aaronvegh** [MasterJ93/ATProtoKit#65]
### Summary

The post data returned by getTimeline is failing to decode because there's no definition for app.bsky.embed.images#view type

### Reproduction Steps

Part of the post results from a getTimeline call yield JSON that can include an embed structure like this:

```json
"embed": {
  "$type": "app.bsky.embed.images#view",
  "images": [
	{
	  "thumb": "https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:2izaurqsrmguegexlfoc7pps/bafkreic523hkuwykiijwbplhmcqyochbx44okvetpl5gnm36chqokpm56m@jpeg",
	  "fullsize": "https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:2izaurqsrmguegexlfoc7pps/bafkreic523hkuwykiijwbplhmcqyochbx44okvetpl5gnm36chqokpm56m@jpeg",
	  "alt": "A fluffy white dog with its head thrown back in a gentle howl."
	}
  ]
},
```

The type `app.bsky.embed.images#view` is not defined by ATProtoKit. On decode, it yields the error:

> Error: typeMismatch(ATProtoKit.ATUnion.EmbedViewUnion, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "feed", intValue: nil), _CodingKey(stringValue: "Index 6", intValue: 6), CodingKeys(stringValue: "post", intValue: nil), CodingKeys(stringValue: "embed", intValue: nil)], debugDescription: "Unknown EmbedViewUnion type", underlyingError: nil))

I tried to look this type up in the docs but had no luck finding it. Hope you can do better.

### Expected Results

Would love to have the type handled?

### Actual Results

It didn't handle it. Hoo boy, this bug report form.

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS

### Operating System Version

macOS 15

### ATProtoKit Version

latest

**Comment by aaronvegh** [comment]
I took a swing at trying to patch this myself, but now I'm wondering if I even know what I'm doing. 🫣

While `app.bsky.embed.images#view` isn't defined, it does appear that `app.bsky.embed.images` is being decoded as-is. And I'm having a hell of a time figuring out what data _is_ causing the indicated problem. Here's the complete set of JSON coming back from the API call that triggers the error; hopefully you can see the unhandled type:

[failed-json.json](https://github.com/user-attachments/files/18045666/failed-json.json)

**Comment by MasterJ93** [comment]
Thanks for the report. I'll look into it.

**Comment by MasterJ93** [comment]
I've made some small changes but I don't think it will solve the issue. I've pushed them into the `develop` branch. I'll have a more in-depth investigation of what's going on after I release 0.21.0 (which should be in a few hours).

**Comment by aaronvegh** [comment]
@MasterJ93 Sorry to say you were quite right: the issue remains unsolved on the current `develop`.

**Comment by MasterJ93** [comment]
As I thought. I'll investigate it more deeply this week and see what's going on. You're still free to make a PR if you do find a fix for this, however.

**Comment by MasterJ93** [comment]
I've tried to replicate your issue, but I was unfortunately unable to do so. I've uploaded the Xcode project in here so you can build and run it:
[ATProtoKitEmbedTest.zip](https://github.com/user-attachments/files/18105687/ATProtoKitEmbedTest.zip)

To clarify, I took your JSON file and put it into the project. Then I decoded it with `AppBskyLexicon.Feed.GetTimelineOutput`. I expected it to give me the same error, but when I ran the project, it decoded everything successfully.

To see that you're having this issue is extremely confusing. I'm going to try my best to continue investigating this issue, though, as this isn't something that should be happening to you.

**Comment by MasterJ93** [comment]
This going to sound really stupid because you probably already did this. But is it possible for you to clean the build folder in your project and try again? I can't see how that would be possible, but maybe there's something in the build folder that's causing this to happen. Again: you've probably already done this, but just in case you haven't, try it and see if it fixes itself.

**Comment by aaronvegh** [comment]
@MasterJ93 Thanks for your investigations so far. I've shaken this thing every which way, without success. I'm super-surprised that you weren't able to replicate my findings, which now worries me that I've overlooked something locally. I've been forced onto other tasks since I filed this ticket, but I'll get back here soon and see if I can suss out more info.

**Comment by aaronvegh** [comment]
@MasterJ93 First off, my apologies for the late reply; life did its thing to me! So I'm *finally* back on this and I have played with the data in your very helpful test app. In my app, which imports ATProtoKit 0.21.1, the attached JSON file (with just one post) triggers this error while decoding:

```
DecodingError
  ▿ typeMismatch : 2 elements
    - .0 : ATProtoKit.ATUnion.EmbedViewUnion
    ▿ .1 : Context
      ▿ codingPath : 4 elements
        - 0 : CodingKeys(stringValue: "feed", intValue: nil)
        ▿ 1 : _CodingKey(stringValue: "Index 0", intValue: 0)
          - index : 0
        - 2 : CodingKeys(stringValue: "post", intValue: nil)
        - 3 : CodingKeys(stringValue: "embed", intValue: nil)
      - debugDescription : "Unknown EmbedViewUnion type"
      - underlyingError : nil
 ```
[data.json](https://github.com/user-attachments/files/18220535/data.json)

However, in your test app, it decodes just fine. 

Interestingly, other post records do trigger decoding errors in your test app. In particular there are text records that contain escaped apostrophes ("for example, it\'s like this") which do make the decoder something-something; I'm not sure if this is happening in my app.

I'm at my wits' end here.

**Comment by MasterJ93** [comment]
Is it possible for you to send me a link to an example post so I can let ATProtoKit individually decode it and I can see for myself?

**Comment by aaronvegh** [comment]
The data file I attached to my last post contains the post that I was currently having trouble with. The URI is `at://did:plc:gr5dh2auxnbohtlju7wfxl7d/app.bsky.feed.post/3lbcdm3q2a222`

**Comment by aaronvegh** [comment]
I have continued to push on this because I'm a masochist, apparently. I've determined that the framework can't decode the above-mentioned post because the incoming JSON doesn't have the properties required by the embedded `starterPack` type. Here's the `record` value of the embed type:

```
[
    "creator": [
        "viewer": [
            "muted": false,
            "blockedBy": false
        ],
        "handle": "veosotano.bsky.social",
        "displayName": "Miro Keller",
        "labels": [
            
        ],
        "createdAt": "2023-11-08T17:50:15.961Z",
        "avatar": "https://cdn.bsky.app/img/avatar/plain/did:plc:gr5dh2auxnbohtlju7wfxl7d/bafkreih2wlqn653xjralwrhyhup45gyn7zmwecx6nhonee3jveivqhyfaa@jpeg",
        "did": "did:plc:gr5dh2auxnbohtlju7wfxl7d"
    ],
    "record": [
        "list": "at://did:plc:gr5dh2auxnbohtlju7wfxl7d/app.bsky.graph.list/3lbcdhe3g2h2k",
        "createdAt": "2024-11-19T11:30:03.001Z",
        "name": "My recommendations to follow",
        "feeds": [
            [
                "uri": "at://did:plc:tenurhgjptubkk5zf5qhi3og/app.bsky.feed.generator/mutuals"
            ],
            [
                "uri": "at://did:plc:tenurhgjptubkk5zf5qhi3og/app.bsky.feed.generator/only-posts"
            ],
            [
                "uri": "at://did:plc:tlewe644hlh3zsdb3pl5zkag/app.bsky.feed.generator/aaaky7nr3qwne"
            ]
        ],
        "description": "This is just my personal list of people on this network, who I think you should follow",
        "$type": "app.bsky.graph.starterpack"
    ],
    "$type": "app.bsky.graph.defs#starterPackViewBasic",
    "indexedAt": "2024-11-19T11:30:04.080Z",
    "uri": "at://did:plc:gr5dh2auxnbohtlju7wfxl7d/app.bsky.graph.starterpack/3lbcdhfc4622t",
    "cid": "bafyreian2br4tjxaabhhllhjvf53vbqtwv5k2zw2jtkt5wz62r6kog7jya",
    "joinedWeekCount": 0,
    "labels": [
        
    ],
    "joinedAllTimeCount": 0
]
```

Note the `feeds` property here; it's expected to be an `AppBskyLexicon.Feed.GeneratorViewDefinition`. The decoder complains here that it's missing a `cid` value, but that's not even a named property of that type, which has a bunch of other properties — and which notably doesn't include the name that IS given, `uri`. I looked up the [JSON reference for this](https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/graph/starterpack.json) and hit the end of my understanding of this whole protocol here:

```
"feeds": {
            "type": "array",
            "maxLength": 3,
            "items": { "type": "ref", "ref": "#feedItem" }
          },
```

So I'm hoping this can suggest a resolution for this type of post and I can go on to less headache-inducing problems. 😬

**Comment by MasterJ93** [comment]
I tested it with the current version (0.22.2) and the example post you've brought up. I can now reproduce the error. This is frustrating because I don't see any apparent issues at first glance.

With the additional information you've given, I'll take this and find a way to figure out what to do in terms of fixing this problem. Thanks for your help.

**Comment by aaronvegh** [comment]
Oh thank goodness. I thought I was going insane. 😂  Thank you!

**Comment by MasterJ93** [comment]
Looking at what you've said more closely, I now understand what the problem is and have fixed the issue: I used the incorrect `struct` and, obviously, this would lead into a decoding issue. I created a new `struct` that should have been made from the start and the issue has went away: that post is now decoding properly.

As for the `feeds` section of `app.bsky.graph.starterpack`, I can explain it, but it's possible you've already figured it out. But just in case:

The `feeds` array property of `app.bsky.graph.starterpack` is pointing to `#feedItem` as the type. `#` simply means it's somewhere in the specific lexicon. Usually you'll see `[NSID]#[type]` (example: `com.atproto.label.defs#label`). This means that the type is in the `com.atproto.label.defs` lexicon and within that lexicon, it's under `label`. The lack of the NSID states the type is in the same lexicon. So to put into context, `#feedItem` is the same as `app.bsky.graph.starterpack#feedItem`.

So where is `feedItem`? It was literally right under our nose:
```json
    "feedItem": {
      "type": "object",
      "required": ["uri"],
      "properties": {
        "uri": { "type": "string", "format": "at-uri" }
      }
    }
```

🤦‍♂️

I feel _so silly_ for not seeing that.

So, when translating this into Swift, and more specifically, within ATProtoKit, this pattern means that there should be a `struct` named `FeedItem` that's inside of `AppBskyLexicon.Graph.StarterpackRecord`.

So, that is what I did:
```swift
/// A feed within the starter pack.
public struct FeedItem: Codable {

    /// The URI of the feed.
    public let uri: String
}
```

I've committed the change and will be pushing it to the `develop` branch soon. But so far, all of the decoding issues appear to be stemmed by earlier mistakes I've made, as well as misreading what the lexicon files are actually saying.

I _really_ need that lexicon generator to be completed: I have no time, but know that these issues will be resolved for the most part when I make it. In any case, please let me know if issue has been fixed. Until then, I'll mark this task as "Review" and wait for your response.

**Comment by aaronvegh** [comment]
@MasterJ93 Can you update this when you have pushed that change to `develop`? Looking forward to trying it out!

**Comment by MasterJ93** [comment]
Looks like I forgot to commit it properly and didn't push the changes. I've checked everything and have pushed the changes. Please try it out and let me know if things are working properly. If so, then I'll close the issue.

**Comment by aaronvegh** [comment]
Confirmed working now! Thank you!
